// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF381ebcaDecodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels(in *jlexer.Lexer, out *SummaryResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "default":
			easyjsonF381ebcaDecodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels1(in, &out.Default)
		case "fallback":
			easyjsonF381ebcaDecodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels1(in, &out.Fallback)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF381ebcaEncodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels(out *jwriter.Writer, in SummaryResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"default\":"
		out.RawString(prefix[1:])
		easyjsonF381ebcaEncodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels1(out, in.Default)
	}
	{
		const prefix string = ",\"fallback\":"
		out.RawString(prefix)
		easyjsonF381ebcaEncodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels1(out, in.Fallback)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SummaryResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF381ebcaEncodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SummaryResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF381ebcaEncodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SummaryResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF381ebcaDecodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SummaryResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF381ebcaDecodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels(l, v)
}
func easyjsonF381ebcaDecodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels1(in *jlexer.Lexer, out *PaymentSummary) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "totalRequests":
			out.TotalRequests = int(in.Int())
		case "totalAmount":
			out.TotalAmount = float64(in.Float64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF381ebcaEncodeGithubComPatrignaniPatrignaniRinhaBackendGoPkgModels1(out *jwriter.Writer, in PaymentSummary) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"totalRequests\":"
		out.RawString(prefix[1:])
		out.Int(int(in.TotalRequests))
	}
	{
		const prefix string = ",\"totalAmount\":"
		out.RawString(prefix)
		out.Float64(float64(in.TotalAmount))
	}
	out.RawByte('}')
}
